### ISSUE TITLE
"code": "100005",     "msg": "request sign illegal"

### ISSUE THREAD

**Issue by holy4040** [exchange-doc/api#3]
Hi 
Trying to create an order. Got this return.
"code": "100005",    "msg": "request sign illegal"

But I use the same sign to cancel or check user account, works fine.

Does anyone know what happens?

Thanks

**Comment by fzx0824** [comment]
Content-Type:application/x-www-form-urlencoded
try this...

**Comment by shuaideshangren** [comment]
可以将要签名的字符串输出，查看下！

> 在 2019年8月20日，下午2:38，holy4040 <notifications@github.com> 写道：
> 
> cancel

**Comment by holy4040** [comment]
Thx all. I found the issue by didn't put params in order.
